// <auto-generated />
namespace UserGroup.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TalkManyToManySpeaker : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TalkManyToManySpeaker));
        
        string IMigrationMetadata.Id
        {
            get { return "201210161739139_TalkManyToManySpeaker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
